name: update-readme
run-name: Updating README.md

on:
  # NOTE sync activity every 7 days (on sunday)
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Sync recent activity
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "⚡ updated README.md w/ my recent GitHub activity"
